# This is a basic workflow to help you get started with Actions
name: Gatsby Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
    # Runs a single command using the runners shell
      - name: Install dependencies
        run: npm i
      - name: Deploy GH Pages
        run: npm run deploy:action
